### ISSUE TITLE
Matching package to framework

### ISSUE THREAD

**Issue by MarkCiliaVincenti** [sa-es-ir/DotNet.RateLimit#19]
Is there a particular reason why you're matching the packages to the framework?

For example Microsoft.Extensions.Caching.Memory 8.0.0 is supported by netstandard2.0, so you may as well have this for all versions. You should try to target as few frameworks as possible in your csproj which would reduce the size of your NuGet package, leading to no performance loss on .NET 8.0 but on earlier frameworks they will make use of potential performance gains from the latest packages.

**Comment by sa-es-ir** [comment]
@MarkCiliaVincenti Thanks for pointing this out. 
Basically, I put those conditions to not break the applications that use the package.
I need to test it for different versions.
